services:
  sharp-api:
    image: carry0987/sharp-api:latest
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=production
      - AUTO_DETECT_WEBP=false
      - ALLOW_FROM_URL=true
      - SAVE_IMAGE=true
      - CACHE=true
      - CHECK_ETAG=false
      - IMAGE_DEBUG=false
    volumes:
      - ./images:/app/images
      - ./processed:/app/processed
